-- MySQL Script generated by MySQL Workbench
-- dom 23 set 2018 18:45:46 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema LES
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `LES` ;

-- -----------------------------------------------------
-- Schema LES
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `LES` DEFAULT CHARACTER SET latin1 ;
USE `LES` ;

-- -----------------------------------------------------
-- Table `LES`.`tb_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LES`.`tb_usuario` ;

CREATE TABLE IF NOT EXISTS `LES`.`tb_usuario` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `apelido` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `dtCadastro` DATE NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `apelido` (`apelido` ASC),
  UNIQUE INDEX `email` (`email` ASC),
  UNIQUE INDEX `cpf` (`cpf` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `LES`.`tb_amigo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LES`.`tb_amigo` ;

CREATE TABLE IF NOT EXISTS `LES`.`tb_amigo` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `idUsuario` INT(11) NOT NULL,
  `idAmigo` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_usuario` (`idUsuario` ASC),
  INDEX `fk_amigo_usuario` (`idAmigo` ASC),
  CONSTRAINT `fk_amigo_usuario`
    FOREIGN KEY (`idAmigo`)
    REFERENCES `LES`.`tb_usuario` (`id`),
  CONSTRAINT `fk_usuario_usuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `LES`.`tb_usuario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `LES`.`tb_endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LES`.`tb_endereco` ;

CREATE TABLE IF NOT EXISTS `LES`.`tb_endereco` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `idUsuario` INT(11) NOT NULL,
  `logradouro` VARCHAR(255) NOT NULL,
  `numero` INT(11) NOT NULL,
  `bairro` VARCHAR(255) NOT NULL,
  `cidade` VARCHAR(255) NOT NULL,
  `estado` VARCHAR(255) NOT NULL,
  `cep` VARCHAR(8) NOT NULL,
  `dtCadastro` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario` (`idUsuario` ASC),
  CONSTRAINT `fk_usuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `LES`.`tb_usuario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `LES`.`tb_evento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LES`.`tb_evento` ;

CREATE TABLE IF NOT EXISTS `LES`.`tb_evento` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `IdEndereco` INT(11) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `dtEvento` DATE NOT NULL,
  `dtCadastro` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_evento_endereco` (`IdEndereco` ASC),
  CONSTRAINT `fk_evento_endereco`
    FOREIGN KEY (`IdEndereco`)
    REFERENCES `LES`.`tb_endereco` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `LES`.`tb_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LES`.`tb_item` ;

CREATE TABLE IF NOT EXISTS `LES`.`tb_item` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `idEvento` INT(11) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `dtCadastro` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_item_evento` (`idEvento` ASC),
  CONSTRAINT `fk_item_evento`
    FOREIGN KEY (`idEvento`)
    REFERENCES `LES`.`tb_evento` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
